(function(){
const DATA=window.CPI_TEAM_PAGES_2026_14U_BOYS||{},UI=window.CPI_TEAM_PAGE_UI||{teams:[],logos:{}},$=id=>document.getElementById(id);
const slugify=v=>String(v||"").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"unknown";
const initials=name=>{const p=String(name||"").match(/[A-Za-z0-9]+/g)||["CPI"];return (p.length===1?p[0].slice(0,3):p.slice(0,3).map(x=>x[0]).join("")).toUpperCase()};
function uniqueTeams(){const m=new Map();(UI.teams||[]).forEach(t=>{if(t&&t.slug&&!m.has(t.slug))m.set(t.slug,t)});if(m.size)return Array.from(m.values());Object.values(DATA.teamIndex||{}).forEach(t=>{if(t&&t.slug&&!m.has(t.slug)){const r=t.ranking||{};m.set(t.slug,{slug:t.slug,team:t.team,club:t.club,rank:r.rank,cpi:r.cpi})}});return Array.from(m.values()).sort((a,b)=>(a.rank||9999)-(b.rank||9999)||String(a.team).localeCompare(b.team))}
function getTeam(key){const idx=DATA.teamIndex||{};return idx[key]||idx[String(key).toLowerCase()]||idx[slugify(key)]||idx["la-jolla-united-a"]||Object.values(idx)[0]}
function rankingOf(t){return t.ranking||t.quality_record||{}}
function recordOf(t){const r=rankingOf(t);if(r.record)return r.record;if(r.record_in_stored_games)return r.record_in_stored_games;let w=0,l=0,tie=0;(t.games_list||[]).forEach(g=>{if(g.result==="W")w++;else if(g.result==="L")l++;else tie++});return `${w}-${l}${tie?`-${tie}`:""}`}
function bestWinOf(t){const r=rankingOf(t);if(r.best_win)return r.best_win;if(r.bestWin)return r.bestWin;if(Array.isArray(r.best_wins)&&r.best_wins.length){const b=r.best_wins[0];return `${b.opponent||"Opponent"} ${b.score||""}`.trim()}const wins=(t.games_list||[]).filter(g=>g.result==="W");if(wins.length){const g=wins[0];return `${g.opponent} ${g.score}`}return "—"}
function groupByEvent(games){const m=new Map();games.forEach(g=>{const k=g.event||"Unknown Event";if(!m.has(k))m.set(k,[]);m.get(k).push(g)});return Array.from(m.entries()).map(([event,items])=>{items.sort((a,b)=>(b.sort_key||0)-(a.sort_key||0));const w=items.filter(g=>g.result==="W").length,l=items.filter(g=>g.result==="L").length,t=items.filter(g=>g.result==="T").length;return{event,items,record:`${w}-${l}${t?`-${t}`:""}`,count:items.length,latest:Math.max(...items.map(g=>g.sort_key||0))}}).sort((a,b)=>b.latest-a.latest)}
function contextText(g){if(g.overall_context)return g.overall_context;const tier=Number(g.tier_num||0);if(tier===1)return"Top overall field";if(tier===2)return"Second overall field context";if(tier>=3)return"Lower overall field context";return"Overall field context"}
function setLogo(team){const wrap=$("teamLogo"),logo=UI.logos&&UI.logos[team.slug||slugify(team.team)];if(logo){wrap.innerHTML=`<img src="${logo}" alt="${team.team} logo" onerror="this.parentElement.innerHTML='<div class=&quot;logo-fallback&quot;>${initials(team.club||team.team)}</div>'">`}else{wrap.innerHTML=`<div class="logo-fallback">${initials(team.club||team.team)}</div>`}}
function fillDropdown(current){const select=$("teamSelect"),teams=uniqueTeams();select.innerHTML=teams.map(t=>`<option value="${t.slug}" ${t.slug===current?"selected":""}>${t.rank?`#${t.rank} — `:""}${t.team}</option>`).join("");select.addEventListener("change",()=>{location.href=`team.html?team=${encodeURIComponent(select.value)}`})}
function fillRankNav(current){const teams=uniqueTeams().filter(t=>t.rank),i=teams.findIndex(t=>t.slug===current),nav=$("rankNav");if(i<0){nav.innerHTML="";return}const prev=teams[i-1],cur=teams[i],next=teams[i+1];nav.innerHTML=`${prev?`<a class="prev" href="team.html?team=${prev.slug}">← #${prev.rank} ${prev.team}</a>`:"<span></span>"}<span class="current">#${cur.rank} ${cur.team}</span>${next?`<a class="next" href="team.html?team=${next.slug}">#${next.rank} ${next.team} →</a>`:"<span></span>"}`}
function render(){const key=new URLSearchParams(location.search).get("team")||"la-jolla-united-a",t=getTeam(key);if(!t)return;const slug=t.slug||slugify(t.team),r=rankingOf(t),games=t.games_list||[],events=groupByEvent(games),latest=events[0],bestWin=bestWinOf(t);document.title=`${t.team} | CPI`;$("teamName").textContent=t.team||"Team";$("teamSubhead").textContent=`${t.club||""} · ${t.age_group||"14U"} ${t.gender||"Boys"}`.replace(/^ · /,"");$("rankValue").textContent=r.rank?`#${r.rank}`:"—";$("cpiValue").textContent=r.cpi||r.qa_cpi||"—";$("recordValue").textContent=recordOf(t);setLogo({...t,slug});fillDropdown(slug);fillRankNav(slug);$("summaryGrid").innerHTML=`<div><dt>Ranking</dt><dd>${r.rank?"#"+r.rank:"Not ranked"}</dd></div><div><dt>CPI</dt><dd>${r.cpi||r.qa_cpi||"—"}</dd></div><div><dt>Record</dt><dd>${recordOf(t)}</dd></div><div><dt>Events</dt><dd>${events.length||"—"}</dd></div><div><dt>Verified Games</dt><dd>${games.length||0}</dd></div><div><dt>Confidence</dt><dd>${r.confidence?r.confidence+"%":"—"}</dd></div>`;$("bestWinCard").innerHTML=bestWin==="—"?"—":`${bestWin}<small>Best available verified win</small>`;$("seasonSnapshot").innerHTML=`<div><dt>Latest Tournament</dt><dd>${latest?latest.event:"—"}</dd></div><div><dt>Latest Record</dt><dd>${latest?latest.record:"—"}</dd></div><div><dt>Top 25 Record</dt><dd>${r.vs_top25||"—"}</dd></div><div><dt>Schedule</dt><dd>${r.schedule_strength??"—"}</dd></div>`;$("timeline").innerHTML=events.map((ev,idx)=>`<div class="timeline-event ${idx===0?"open":""}"><button class="timeline-toggle" type="button"><span><strong>${ev.event}</strong><span>${ev.count} verified game${ev.count===1?"":"s"}</span></span><span class="event-record">${ev.record}</span><span class="event-count">${ev.count} games</span></button><div class="timeline-games">${ev.items.map(g=>`<div class="timeline-game"><span class="result-pill ${g.result||"T"}">${g.result||"T"}</span><span>${g.result==="W"?"def.":g.result==="L"?"lost to":"tied"} ${g.opponent||"Opponent"}<br><small>${contextText(g)}</small></span><span class="score">${g.score||""}</span><span>${g.round||""}</span></div>`).join("")}</div></div>`).join("");document.querySelectorAll(".timeline-toggle").forEach(btn=>btn.addEventListener("click",()=>btn.closest(".timeline-event").classList.toggle("open")));$("resultsTable").innerHTML=games.map(g=>`<tr><td>${g.event||""}</td><td>${g.opponent||""}</td><td>${g.result||""}</td><td>${g.score||""}</td><td>${contextText(g)}</td></tr>`).join("")}
render();
})();